tap "hashicorp/tap"
tap "heroku/brew"
tap "sindrel/tap"
tap "stripe/stripe-cli"
tap "teamookla/speedtest"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "glib"
brew "libyaml"
brew "cocoapods"
brew "colima", restart_service: :changed
brew "ctags"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "folly"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "edencommon"
brew "eza"
brew "gh"
brew "git"
brew "go"
brew "harfbuzz"
brew "gradle"
brew "graphviz"
brew "node"
brew "jupyterlab"
brew "ldns"
brew "libfido2"
brew "mas"
brew "mvfst"
brew "neovim"
brew "nvm"
brew "ollama"
brew "openjdk@21"
brew "openssh"
brew "postgresql@14"
brew "pwgen"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.10"
brew "python@3.11"
brew "python@3.9"
brew "rbenv"
brew "redis"
brew "spaceship"
brew "tree"
brew "watchman"
brew "yarn"
brew "zsh-completions"
brew "hashicorp/tap/terraform"
brew "heroku/brew/heroku"
brew "sindrel/tap/excalidraw-converter"
brew "stripe/stripe-cli/stripe"
brew "teamookla/speedtest/speedtest"
cask "1password-cli"
cask "anytype"
cask "apparency"
cask "bruno"
cask "db-browser-for-sqlite"
cask "discord"
cask "drawio"
cask "font-fira-code-nerd-font"
cask "gcloud-cli"
cask "insomnia"
cask "kindle"
cask "logseq"
cask "mockoon"
cask "monitorcontrol"
cask "ngrok"
cask "notion"
cask "pgadmin4"
cask "postman"
cask "slack"
cask "spectacle"
cask "spotify"
cask "stats"
cask "telegram"
cask "visual-studio-code"
cask "whatsapp"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Clocker", id: 1056643111
mas "Developer", id: 640199958
mas "GarageBand", id: 682658836
mas "Hand Mirror", id: 1502839586
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "Kindle Classic", id: 405399194
mas "Meeter", id: 1510445899
mas "Numbers", id: 409203825
mas "Okta Verify", id: 490179405
mas "Pages", id: 409201541
mas "Prime Video", id: 545519333
mas "Swift Playground", id: 1496833156
mas "TickTick", id: 966085870
mas "Todoist", id: 585829637
mas "Toggl Track", id: 1291898086
mas "Trello", id: 1278508951
mas "Xcode", id: 497799835
vscode "4ops.terraform"
vscode "aliariff.vscode-erb-beautify"
vscode "bradlc.vscode-tailwindcss"
vscode "catppuccin.catppuccin-vsc"
vscode "catppuccin.catppuccin-vsc-icons"
vscode "catppuccin.catppuccin-vsc-pack"
vscode "clemenspeters.format-json"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "dracula-theme.theme-dracula"
vscode "esbenp.prettier-vscode"
vscode "frhtylcn.pythonsnippets"
vscode "george-alisson.html-preview-vscode"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "golang.go"
vscode "google.geminicodeassist"
vscode "grapecity.gc-excelviewer"
vscode "hashicorp.terraform"
vscode "jackz.json-parser"
vscode "kevinrose.vsc-python-indent"
vscode "koichisasada.vscode-rdbg"
vscode "mathiasfrohlich.kotlin"
vscode "mechatroner.rainbow-csv"
vscode "mikestead.dotenv"
vscode "mohsen1.prettify-json"
vscode "mongodb.mongodb-vscode"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.cpptools"
vscode "msjsdiag.vscode-react-native"
vscode "nativebase.nativebase-v3-vscode-extension"
vscode "pkief.material-icon-theme"
vscode "prisma.prisma"
vscode "rangav.vscode-thunder-client"
vscode "redhat.java"
vscode "rust-lang.rust-analyzer"
vscode "saoudrizwan.claude-dev"
vscode "setobiralo.erb-commenter"
vscode "shanehofstetter.rails-open-partial"
vscode "shopify.ruby-lsp"
vscode "simonsiefke.svg-preview"
vscode "tamasfe.even-better-toml"
vscode "tehpeng.diagramspreviewer"
vscode "tomoki1207.pdf"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "wallabyjs.quokka-vscode"
vscode "yoavbls.pretty-ts-errors"
vscode "zerefdev.todo-highlighter"
go "golang.org/x/tools/cmd/godoc"
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
cargo "cargo-watch"
